### ISSUE TITLE
Review and update your project plan with your mentor

### ISSUE THREAD

**Issue by sredas** [sredas/transcribe#8]
- [ ] Prepare questions to ask
- [ ] Meet with mentor 
- [ ] Update project plan based on feedback
